### ISSUE TITLE
python install on osx fail

### ISSUE THREAD

**Issue by jovo** [flashxio/knor#50]
```
Joshuas-MBP:10049562jbnxhkqmhpqg jovo$ pip install knor
Collecting knor
  Downloading knor-0.0.1a10.tar.gz (110kB)
    100% |████████████████████████████████| 112kB 1.8MB/s 
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/qb/5wvt890j747c03m0_fg63wch0000gn/T/pip-build-okma13ts/knor/setup.py", line 136
        raise DistutilsSetupError, \
                                 ^
    SyntaxError: invalid syntax
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/qb/5wvt890j747c03m0_fg63wch0000gn/T/pip-build-okma13ts/knor/

```

**Comment by jovo** [comment]
not sure how to fail for R, but i assume there is a way :)

**Comment by disa-mhembere** [comment]
is your default python 2.7?

**Comment by disa-mhembere** [comment]
This is in the docs to be merged but you'll also need to:
`brew install boost`

**Comment by jovo** [comment]
@disa-mhembere tried to install python, still don't see any instructions.
i tried pip:

```
Joshuas-MacBook-Pro:~ jovo$ pip install knor
Collecting knor
  Using cached knor-0.0.1a17.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/qb/5wvt890j747c03m0_fg63wch0000gn/T/pip-build-EaKSVr/knor/setup.py", line 12, in <module>
        from Cython.Build import cythonize
    ImportError: No module named Cython.Build
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/qb/5wvt890j747c03m0_fg63wch0000gn/T/pip-build-EaKSVr/knor/
```

**Comment by disa-mhembere** [comment]
Ideally there should be no instructions. Just: `pip install knor`.

Your error looks like you didn't install cython though.

I will add frequently found errors soon.

On Aug 1, 2017 4:30 PM, "joshua vogelstein" <notifications@github.com>
wrote:

@disa-mhembere <https://github.com/disa-mhembere> tried to install python,
still don't see any instructions.
i tried pip:

Joshuas-MacBook-Pro:~ jovo$ pip install knor
Collecting knor
  Using cached knor-0.0.1a17.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/qb/5wvt890j747c03m0_fg63wch0000gn/T/pip-build-EaKSVr/knor/setup.py",
line 12, in <module>
        from Cython.Build import cythonize
    ImportError: No module named Cython.Build

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in
/private/var/folders/qb/5wvt890j747c03m0_fg63wch0000gn/T/pip-build-EaKSVr/knor/

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/flashxio/knor/issues/50#issuecomment-319387273>, or mute
the thread

**Comment by jovo** [comment]
cython install seems to have fixed the problem!

here is an example readme file: https://github.com/neurodata-papers/MGC

note that all the dependencies are explicitly stated, which OS etc it works on....

**Comment by disa-mhembere** [comment]
Glad it installed :)

On Aug 1, 2017 4:57 PM, "joshua vogelstein" <notifications@github.com>
wrote:

cython install seems to have fixed the problem!

here is an example readme file: https://github.com/neurodata-papers/MGC

note that all the dependencies are explicitly stated, which OS etc it works
on....

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/flashxio/knor/issues/50#issuecomment-319395829>, or mute
the thread
