### ISSUE TITLE
how do i run in either python or R?

### ISSUE THREAD

**Issue by jovo** [flashxio/knor#52]
i don't see instructions for how to actually run it in R or python.

(note - i think you are supposed to be doing a wedding, not responding to these git issues :-)

**Comment by disa-mhembere** [comment]
Yes -- I kept changing the interface, but now it is stable and I will
document appropriately!

And I can multitask can't I :)

On Aug 1, 2017 6:21 PM, "joshua vogelstein" <notifications@github.com>
waarzaawar,e,aarzaa

i don't see instructions for how to actually run it in R or python.

(note - i think you are supposed to be doing a wedding, not responding to
these git issues :-)

—
You are receiving this because you were assigned.
Reply to this email directly, view it on GitHub
<https://github.com/flashxio/knor/issues/52>, or mute the thread

**Comment by disa-mhembere** [comment]
Now documented in READMEs
